config/routes.rb
NI::Application.routes.draw do

  RESPOND_403.each do |r2|
    get "/#{r2}", to: proc { [403, {}, ['']] }
  end

  resources :categories, :only => [:index, :show, :edit, :update]
  get 'update_categories_colours' => 'categories#colours'

  get "guest_passes/index"

  get "subscriptions/update"

  get "settings/index"

  get "settings/update"

  get "/sitemap.xml", :controller => "sitemap", :action => "index"

  get "users/re_sign_in"

  devise_for :users, :controllers => { :registrations => "registrations", :sessions => "sessions", :passwords => "passwords" } #, :path_names => { :sign_up => "subscribe" }

  devise_scope :user do
    get "/uk_login" => "devise/sessions#new_uk"
  end

  post "users/:id(.:format)", :to => 'users#show', :as => :user
  resources :users, :only => [:show]

  resources :subscriptions do
    get :show
    new do
      get :express
    end
  end

  post "issues/:id(.:format)", :to => 'issues#show', :as => :issue

  resources :issues do
    get :import
    get :import_extra
    get :import_images
    get :email
    get :email_non_subscribers
    get :email_others
    get :email_renew
    get :email_special
    get :zip
    post :setup_push_notification
    get :tweet_issue
    get :wall_post_issue
    get :email_issue
    resources :articles do
      resources :favourites, :only => [:create, :destroy]
      resources :guest_passes, :only => [:create, :destroy]
      get :body
      post :body
      post :body_android
      get :import
      get :import_images
      get :generate_from_source
      resources :images do
        collection { post :sort }
      end
      post :send_push_notification
      get :tweet
      get :wall_post
      get :email_article
      get :ios_share
      post :ios_share
      get :android_share
      post :android_share
      get :hide_images
    end
    resources :purchases, :only => [:new, :create, :show] do
      new do
        get :express
      end
    end
  end

  get 'search' => 'articles#search'
  get 'popular' => 'articles#popular'
  get 'quick_reads' => 'articles#quick_reads'

  resource :payment_notifications, :only => [:create]

  resource :push_registrations, only: [:create, :destroy]

  namespace :admin do
    root :to => "base#index"
    get "welcome_email" => "base#welcome_email"
    get "reset_password_instructions_email" => "base#reset_password_instructions_email"
    get "subscription_email" => "base#subscription_email"
    get "magazine_purchase_email" => "base#magazine_purchase_email"
    get "admin_email" => "base#admin_email"
    get "delete_cache" => "base#delete_cache"
    get "users/update_csv" => "users#update_csv"
    get "users/download_csv" => "users#download_csv"
    get "users/search" => "users#search"
    resources :users do
      get :free_subscription
      get :crowdfunding_subscription
      get :media_subscription
      get :make_institutional
      get :free_silent_subscription
      post :free_silent_subscription
      get :become
    end
    resources :subscriptions, :only => [:update]
    resources :settings, :only => [:index, :update], :constraints => { :id => /[a-z_]+/ }
    resources :guest_passes, :only => [:index]
    resources :push_registrations, :only => [:index]
    namespace :push_registrations do
      get :import
    end
    resources :push_notifications, :only => [:index, :destroy]
    namespace :push_notifications do
      post :run_delayed_jobs
      post :send_notifications
    end
  end

  namespace :institution do
    root :to => "base#index"
    resources :users
  end

  get "home/index"
  get "newsstand" => "home#newsstand"
  get "free" => "home#free"
  get "inapp" => "home#inapp"
  get "google_merchant_feed" => "home#google_merchant_feed"
  get "apple_news" => "home#apple_news"
  get "apple-app-site-association" => "home#apple_app_site_association"
  get "rss" => "home#apple_news"
  get "latest_cover" => "home#latest_cover"
  get "tweet_url" => "home#tweet_url"
  get "wall_post_url" => "home#wall_post_url"
  get "email_url" => "home#email_url"

  root :to => 'home#index'

  get '/perma_article/:id' => 'articles#show'

  get 'pages', to: 'pages#index'
  get ':id', to: 'pages#show', as: :page
  patch ':id', to: 'pages#update'#, as: :page
  delete ':id', to: 'pages#destroy'#, as: :page

  resources :pages, except: :show

end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController

  # Cancan authorisation
  load_and_authorize_resource :except => [:index]

  newrelic_ignore :only => [:email, :email_non_subscribers, :email_others, :email_renew, :email_special]
  # newrelic_ignore_enduser :only => [:email, :email_non_subscribers, :email_others, :email_renew]
  # NOTE: if setting up another email, don't forget to add it to ability.rb too :-)

  # :show So that iOS can post, :index so that issues.json jquery works
  skip_before_filter :verify_authenticity_token, :only => [:show, :index]

  # Devise authorisation
  # before_filter :authenticate_user!, :except => [:show, :index]

  # GET /issues
  # GET /issues.json

  def import
    @issue = Issue.find(params[:issue_id])
    @issue.import_articles_from_bricolage(nil)
    redirect_to issue_path(@issue)
  end

  def import_extra
    options = { special_type: params[:article_type], unpublished: true }
    @issue = Issue.find(params[:issue_id])
    @issue.import_articles_from_bricolage(options)
    redirect_to issue_path(@issue)
  end

  def import_images
    @issue = Issue.find(params[:issue_id])
    @issue.articles.each do |article|
      article.import_media_from_bricolage
    end
    redirect_to issue_path(@issue)
  end

  def import_categories
    @issue = Issue.find(params[:issue_id])
    @issue.articles.each do |article|
      article.import_categories_from_source
    end
    redirect_to issue_path(@issue)
  end

  def index
    # @issues = Issue.all
    # Pagination
    # @issues = Issue.order("release").reverse_order.page(params[:page]).per(2)
    # Search
    # @issues = Issue.search(params)
    # TOFIX: TODO: Search + pagination?
    # @issues = Issue.order("release").reverse_order.page(params[:page]).per(2).search(params)

    @issues = Issue.search(params, current_user.try(:admin?))

    # Set meta tags
    @page_title = "Magazine archive"
    @page_description = "An archive of all the New Internationalist magazines available as digital editions."

    set_meta_tags :title => @page_title,
                  :description => @page_description,
                  :keywords => "new, internationalist, magazine, archive, digital, edition",
                  :canonical => issues_url,
                  :alternate => [
                    {:href => "android-app://#{ENV['GOOGLE_PLAY_APP_PACKAGE_NAME']}/newint/issues"}, 
                    {:href => "ios-app://#{ENV['ITUNES_APP_ID']}/newint/issues"},
                    {:href => rss_url(format: :xml), :type => 'application/rss+xml', :title => 'RSS'}
                  ],
                  :fb => {
                    :app_id => ENV["FACEBOOK_APP_ID"]
                  },
                  :open_graph => {
                    :title => @page_title,
                    :description => @page_description,
                    #:type  => :magazine,
                    :url   => issues_url,
                    :image => Issue.latest.try(:cover_url).to_s,
                    :site_name => "New Internationalist Magazine Digital Edition"
                  },
                  :twitter => {
                    :card => "summary",
                    :site => "@#{ENV["TWITTER_NAME"]}",
                    :creator => "@#{ENV["TWITTER_NAME"]}",
                    :title => @page_title,
                    :description => @page_description,
                    :image => {
                      :src => Issue.latest.try(:cover_url).to_s
                    },
                    :app => {
                      :name => {
                        :iphone => ENV["ITUNES_APP_NAME"],
                        :ipad => ENV["ITUNES_APP_NAME"]
                      },
                      :id => {
                        :iphone => ENV["ITUNES_APP_ID"],
                        :ipad => ENV["ITUNES_APP_ID"]
                      },
                      :url => {
                        :iphone => "newint://issues",
                        :ipad => "newint://issues"
                      }
                    }
                  }

    respond_to do |format|
      format.html # index.html.erb
      #format.json { render json: @issues, callback: params[:callback] }
      format.json { 
        if not params[:query].blank?
          @json_issues = @issues
        else
          @json_issues = Issue.where(published: true).order(:release).reverse_order
        end
        render callback: params[:callback], json: Issue.issues_index_to_json(@json_issues) 
      }
    end
  end

  def email
    @issue = Issue.find(params[:issue_id])

    respond_to do |format|
      format.html { render :layout => 'email' }
      format.text { render :layout => false }
      format.mjml { render :layout => false }
    end
  end

  def email_non_subscribers
    @issue = Issue.find(params[:issue_id])

    respond_to do |format|
      format.html { render :layout => 'email' }
      format.text { render :layout => false }
      format.mjml { render :layout => false }
    end
  end

  def email_others
    @issue = Issue.find(params[:issue_id])

    respond_to do |format|
      format.html { render :layout => 'email' }
      format.text { render :layout => false }
      format.mjml { render :layout => false }
    end
  end

  def email_renew
    @issue = Issue.find(params[:issue_id])

    respond_to do |format|
      format.html { render :layout => 'email' }
      format.text { render :layout => false }
      format.mjml { render :layout => false }
    end
  end

  def email_special
    respond_to do |format|
      format.text { render :layout => false }
      format.mjml { render :layout => false }
    end
  end

  def zip
    @issue = Issue.find(params[:issue_id])
    @issue.zip_for_ios
    redirect_to @issue, notice: "Zip created."
  end

  def setup_push_notification
    # Setup a push notification
    @issue = Issue.find(params[:issue_id])
    Issue.delay.setup_push_notifications(params)
    # Start jobs in the background (doesn't seem to do it as a background job)
    # view_context.start_delayed_jobs
    redirect_to admin_push_notifications_path, notice: "Push notifications are being created as a delayed job - next set the delayed jobs running."
  end

  # GET /issues/1
  # GET /issues/1.json
  def show
    # @issue = Issue.find(params[:id])
    # TOFIX: Sort articles by :position using jquery

    # Load section definitions
    #sections_of_articles_definitions
    #moved to the model

    # Limit showing just last six web exclusives & two blogs unless you're an admin
    @blogs = @issue.blogs.last(2)
    @web_exclusives = @issue.web_exclusive.last(6)
    if current_user and current_user.admin?
      @blogs = @issue.blogs
      @web_exclusives = @issue.web_exclusive
    end

    @categories = @issue.all_articles_categories

    redesigned = ApplicationHelper.redesigned?(@issue.release)

    @features_name = 'Features'
    if redesigned
      @features_name = 'The Big Story'
    end
    
    # Set meta tags
    @page_title = @issue.title
    @page_description = "#{@issue.release.strftime("%B, %Y")} - #{ActionView::Base.full_sanitizer.sanitize(@issue.keynote.try(:teaser))}"

    set_meta_tags :site => 'New Internationalist',
                  :title => @page_title,
                  :description => @page_description,
                  :keywords => "new, internationalist, magazine, digital, edition, #{@issue.title}",
                  :canonical => issue_url(@issue),
                  :alternate => [
                    {:href => "android-app://#{ENV['GOOGLE_PLAY_APP_PACKAGE_NAME']}/newint/issues/#{@issue.id}"}, 
                    {:href => "ios-app://#{ENV['ITUNES_APP_ID']}/newint/issues/#{@issue.id}"},
                    {:href => rss_url(format: :xml), :type => 'application/rss+xml', :title => 'RSS'}
                  ],
                  :fb => {
                    :app_id => ENV["FACEBOOK_APP_ID"]
                  },
                  :open_graph => {
                    :title => @page_title,
                    :description => @page_description,
                    #:type  => :magazine,
                    :url   => issue_url(@issue),
                    :image => @issue.cover_url.to_s,
                    :site_name => "New Internationalist Magazine Digital Edition"
                  },
                  :twitter => {
                    :card => "summary",
                    :site => "@#{ENV["TWITTER_NAME"]}",
                    :creator => "@#{ENV["TWITTER_NAME"]}",
                    :title => @page_title,
                    :description => @page_description,
                    :image => {
                      :src => @issue.cover_url.to_s
                    },
                    :app => {
                      :name => {
                        :iphone => ENV["ITUNES_APP_NAME"],
                        :ipad => ENV["ITUNES_APP_NAME"]
                      },
                      :id => {
                        :iphone => ENV["ITUNES_APP_ID"],
                        :ipad => ENV["ITUNES_APP_ID"]
                      },
                      :url => {
                        :iphone => "newint://issues/#{@issue.id}",
                        :ipad => "newint://issues/#{@issue.id}"
                      }
                    }
                  }

    respond_to do |format|
      format.html # show.html.erb
      if request.post?
        if request_has_valid_rails_subscription or request_has_purchased_rails_issue or request_has_valid_itunes_subscription or request_has_valid_google_play_receipt
          zip_url_for_json = @issue.zip.url
          if Rails.env.development?
            zip_url_for_json = "#{request.protocol}#{request.host_with_port}#{@issue.zip.url}"
          end
          format.json { render json: { :id => @issue.id, :name => @issue.number, :publication => @issue.release, :zipURL => zip_url_for_json } }
        else
          format.json { render nothing: true, status: :forbidden }
        end
      else

app/helpers/issues_helper.rb
module IssuesHelper
	# Adds CSS class to unpublished issues in issues index.
	def unpublished(issue)
        if not issue.published
            " issue-unpublished"
        end
    end
end

app/views/issues/_article_email.html.erb
<% if not article_email.featured_image.blank? %>
  <%= link_to retina_image_tag(article_email.featured_image_url(:thumb).to_s, :class => 'article-thumb', :alt => "#{strip_tags(article_email.featured_image_caption)}", :title => "#{strip_tags(article_email.featured_image_caption)}", :size => "80x80"), issue_article_path(@issue,article_email) %>
<% elsif not article_email.images.first.blank? %>
  <%= link_to retina_image_tag(article_email.images.first.data_url(:thumb).to_s, :class => 'article-thumb', :alt => "", :title => "", :size => "80x80"), issue_article_path(@issue,article_email) %>
<% end %>
<h4><%= link_to article_email.title, issue_article_path(@issue,article_email) %></h4>
<p><%= simple_format article_email.teaser %></p>

app/views/issues/show.html.erb
<%- model_class = Issue -%>

<% if user_signed_in? and can? :update, @issue %>
<div class="edit-issue-buttons">
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
                edit_issue_path(@issue), :class => 'btn btn-primary btn-xs' %>
  <% if user_signed_in? and can? :destroy, @issue %>
    <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
          issue_path(@issue),
          :method => 'delete',
          :data => {:confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure? Becuase if you delete this Issue, it will also delete all of the Articles and any purchases of this Issue. Are you really sure?'))},
          :class => 'btn btn-xs btn-danger' %>
  <% end %>
   | 
  <% if user_signed_in? and can? :create, Article %>
    <%= link_to 'New Article', new_issue_article_path(@issue), :class => 'btn btn-xs btn-success' %>
     |
    <%= link_to 'Import Articles', issue_import_path(@issue), :class => 'btn btn-xs btn-warning',
      :data => {:confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure? Because this will try and import all the articles from Bricolage.'))} %>
     |
    <%= link_to 'Import Images', issue_import_images_path(@issue), :class => 'btn btn-xs btn-warning',
      :data => {:confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure? This will try and import all the images for each article listed here.'))} %>
    <hr />
    <%= link_to 'Import Blogs', issue_import_extra_path(@issue, article_type: "blog"), :class => 'btn btn-xs btn-warning',
      :data => {:confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure? This will import the blogs from Bricolage.'))} %>
     |
     <%= link_to 'Import Web Exclusives', issue_import_extra_path(@issue, article_type: "web-exclusive"), :class => 'btn btn-xs btn-warning',
      :data => {:confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure? This will import the web-exclusives from Bricolage.'))} %>
    <hr />
    <%= link_to 'Email current subscriber', issue_email_path(@issue, :mjml), :class => 'btn btn-default btn-xs' %>
     |
    <%= link_to 'Text current subscriber', issue_email_path(@issue, :text), :class => 'btn btn-default btn-xs' %>
    <hr />
    <%= link_to 'Email non-subscriber', issue_email_non_subscribers_path(@issue, :mjml), :class => 'btn btn-default btn-xs' %>
     |
    <%= link_to 'Text non-subscriber', issue_email_non_subscribers_path(@issue, :text), :class => 'btn btn-default btn-xs' %>
    <hr />
    <%= link_to 'Email others', issue_email_others_path(@issue, :mjml), :class => 'btn btn-default btn-xs' %>
     |
    <%= link_to 'Text others', issue_email_others_path(@issue, :text), :class => 'btn btn-default btn-xs' %>
    <hr />
    <%= link_to 'Renew please', issue_email_renew_path(@issue, :mjml), :class => 'btn btn-default btn-xs' %>
     |
    <%= link_to 'Text renew please', issue_email_renew_path(@issue, :text), :class => 'btn btn-default btn-xs' %>
    <hr />
    <%= link_to 'Subscribe special', issue_email_special_path(@issue, :mjml), :class => 'btn btn-default btn-xs' %>
     |
    <%= link_to 'Text subscribe special', issue_email_special_path(@issue, :text), :class => 'btn btn-default btn-xs' %>
    <hr />
    <p><b>Create a zip file for the iOS app</b></p>
    <%= link_to 'Zip up this issue', issue_zip_path(@issue), :class => 'btn btn-default btn-xs' %>
    <hr />

    <p><b>iOS &amp; Android Push Notification</b></p>

    <% if not @issue.published? %>
      <p>This issue has to be published to send a push notification.</p>
    <% elsif @issue.notification_sent %>
      <p><b>Sent</b>: <%= @issue.notification_sent.in_time_zone("Australia/Adelaide").strftime("%d/%m/%Y at %I:%M%p") %><br />(<%= @issue.notification_sent.strftime("%d/%m/%Y at %I:%M%p GMT") %>)</p>
    <% else %>
      <%= simple_form_for issue_setup_push_notification_path(@issue), :url => issue_setup_push_notification_path(@issue) do |f| %>
        <%= f.input :scheduled_datetime, as: :datetime, required: false, label: 'Scheduled for: (UTC, GMT timezone)' %>
        <%= f.input :device_id, :placeholder => 'Push to single user device_id', required: false %>
        <%= f.input :test_device_android, as: :boolean %>
        <%= f.input :alert_text, :placeholder => 'Message', required: false %>
        <%= button_tag(type: 'submit', class: "btn btn-warning", data: {confirm: "Are you sure? Check the spelling again!\n\nIt automatically includes: #{@issue.push_notification_text}"}) do %>
          Setup Push notifications
        <% end %>
      <% end %>
    <% end %>

  <% end %>
</div>
<% end %>

<% if user_signed_in? and can? :update, @issue %>
  <% if not @issue.uncategorised.empty? %>
    <div class="articles-not-categorised-for-display">
      <h3>Articles not displayed</h3>
      <% @issue.uncategorised.each do |article| %>
        <div class="issue-article" itemscope itemtype="http://schema.org/Article">
          <%= render :partial => "article_uncategorised", :locals => { :article => article } %>
        </div>
      <% end %>
    </div>
  <% end %>
<% end %>

<div class="row issue-top-box" itemscope itemtype="http://schema.org/Product">
  <div class="col-sm-4 issue-title">
    <!-- Magazine cover -->
    <%= retina_image_tag(@issue.cover_url(:home).to_s, :class => 'shadow home-latest-cover', :alt => "NI #{@issue.number} - #{@issue.title} - #{@issue.release.strftime("%B, %Y")}", :itemprop => "image", :title => "NI #{@issue.number} - #{@issue.title} - #{@issue.release.strftime("%B, %Y")}", :rel => "tooltip", :width => 282, :height => 400) %>
    <!-- Share links -->
    <h2><%= render :partial => "share_links", :object => @issue %></h2>

    <% if cannot? :read, @issue.keynote %>
      <p><%= link_to "Buy this issue $#{cents_to_dollars(Settings.issue_price)}", new_issue_purchase_path(@issue), :class => 'btn btn-default' %></p>
    <% end %>
    <% if not current_user.try(:subscriber?) %>
      <p><%= link_to "Subscribe from $#{cents_to_dollars(Subscription.calculate_subscription_price(3,autodebit: true))}", page_path("subscribe"), :class => 'btn btn-success' %></p>
    <% end %>
  </div>
  <div class="col-sm-8">
    <h1 itemprop="name"><%= @issue.title %></h1>
    <meta itemprop="description" content="<%= @page_description %>">
    <meta itemprop="brand" content="New Internationalist">
    <meta itemprop="logo" content="<%= asset_url("favicon-196x196.png") %>">
    <meta itemprop="releaseDate" content="<%= @issue.release.to_time.iso8601 %>">
    <span itemscope itemtype="http://schema.org/Offer">
      <link itemprop="availability" href="http://schema.org/InStock">
      <meta itemprop="sku" content="<%= @issue.number %>">
      <meta itemprop="priceCurrency" content="AUD">
      <meta itemprop="price" content="<%= cents_to_dollars(Settings.issue_price) %>">
    </span>
    <% if @issue.editors_letter != "" %>
      <h3>A note from the editor</h3>
      <div class="table-of-contents-editors-letter">
        <div class="home-editors-photo-container">
          <%= retina_image_tag @issue.editors_photo_url(:thumb).to_s, :class => 'home-editors-photo', :alt => "#{@issue.editors_name}", :title => "#{@issue.editors_name}", :width => "100" %>
        </div>
        <%= simple_format @issue.editors_letter %>
        <p><strong><%= @issue.editors_name %></strong> for the New Internationalist co-operative.<br /><a href="http://www.newint.org">www.newint.org</a></p>
      </div>
    <% end %>
  </div>
</div>

<div class="row issue-keynote">
  <div class="col-sm-12 big-story">
    <h3>The big story</h3>
  </div>
  <div itemscope itemtype="http://schema.org/Article">
    <% if @issue.keynote %>
      <%= render :partial => "article_keynote", :locals => { :article => @issue.keynote } %>
    <% end %>
  </div>
</div>

<%= render :partial => "shared/account_sign_up" %>

<hr />

<div class="row">
  <nav class="col-sm-12 latest-issue-categories">
    <h6>What's inside this magazine</h6>
    <ul class="breadcrumb">
    <% @categories.each do |category| %>
      <li><%= link_to category.short_display_name, category_path(category), :class => 'label' %></li>
      <% if user_signed_in? and can? :manage, category %><li><%= category.name %></li><% end %>
    <% end %>
    </ul>
  </nav>
</div>

<hr />

<% if not @issue.features.empty? %>

  <h3><%= @features_name %></h3>

  <div class="row">
    <% @issue.features.each_with_index do |article, index| %>
      <% if index % 3 == 0 %>
  </div>
  <div class="row">
      <% end %>
      <div class="col-sm-4">
        <div class="issue-article" itemscope itemtype="http://schema.org/Article">
          <%= render :partial => "article", :locals => { :article => article } %>
        </div>
      </div>
    <% end %>
  </div>

  <hr />

<% end %>

<% if not @web_exclusives.empty? %>

  <h3>Web exclusives</h3>

  <div class="row">
    <% @web_exclusives.each_with_index do |article, index| %>
      <% if index % 3 == 0 %>
  </div>
  <div class="row">
      <% end %>
      <div class="col-sm-4">
        <div class="issue-article" itemscope itemtype="http://schema.org/Article">
          <%= render :partial => "article", :locals => { :article => article } %>
        </div>
      </div>
    <% end %>
  </div>

  <hr />

<% end %>

<% if not @issue.alternatives.empty? %>

  <h3>Alternatives</h3>

  <div class="row">
    <% @issue.alternatives.each_with_index do |article, index| %>
      <% if index % 3 == 0 %>
  </div>
  <div class="row">
      <% end %>
      <div class="col-sm-4">
        <div class="issue-article" itemscope itemtype="http://schema.org/Article">
          <%= render :partial => "article", :locals => { :article => article } %>
        </div>
      </div>
    <% end %>
  </div>

  <hr />

<% end %>

<% if not @blogs.empty? %>

  <h3>Blogs</h3>

  <div class="row">
    <% @blogs.each_with_index do |article, index| %>
      <% if index % 3 == 0 %>
  </div>
  <div class="row">
      <% end %>
      <div class="col-sm-4">
        <div class="issue-article" itemscope itemtype="http://schema.org/Article">
          <%= render :partial => "article", :locals => { :article => article } %>
        </div>
      </div>
    <% end %>
  </div>

  <hr />

<% end %>

<% if not @issue.opinion.empty? %>

  <h3>Opinion</h3>

  <div class="row">
    <% @issue.opinion.each_with_index do |article, index| %>
      <% if index % 3 == 0 %>
  </div>
  <div class="row">
      <% end %>
      <div class="col-sm-4">
        <div class="issue-article" itemscope itemtype="http://schema.org/Article">
          <%= render :partial => "article", :locals => { :article => article } %>
        </div>
      </div>
    <% end %>
  </div>

  <hr />

<% end %>

<% if not @issue.agendas.empty? %>

  <h3>Agenda</h3>

  <div class="row">
    <% @issue.agendas.each_with_index do |article, index| %>
      <% if index % 3 == 0 %>
  </div>
  <div class="row">
      <% end %>
      <div class="col-sm-4">
        <div class="issue-article" itemscope itemtype="http://schema.org/Article">
          <%= render :partial => "article", :locals => { :article => article } %>
        </div>
      </div>
    <% end %>
  </div>

  <hr />

<% end %>

<% if not @issue.currents.empty? %>

  <h3>Currents</h3>

  <div class="row">
    <% @issue.currents.each_with_index do |article, index| %>
      <% if index % 3 == 0 %>
  </div>
  <div class="row">
      <% end %>
      <div class="col-sm-4">
        <div class="issue-article" itemscope itemtype="http://schema.org/Article">
          <%= render :partial => "article", :locals => { :article => article } %>
        </div>
      </div>
    <% end %>
  </div>

  <hr />

<% end %>

<% if not @issue.videos.empty? %>

  <h3>Videos</h3>

  <div class="row">
    <% @issue.videos.each_with_index do |article, index| %>
      <% if index % 3 == 0 %>
  </div>
  <div class="row">
      <% end %>
      <div class="col-sm-4">
        <div class="issue-article" itemscope itemtype="http://schema.org/Article">
          <%= render :partial => "article", :locals => { :article => article } %>
        </div>
      </div>
    <% end %>
  </div>

  <hr />

<% end %>

<% if not @issue.regulars.empty? %>

  <h3>Regulars</h3>

  <div class="row">
    <% @issue.regulars.each_with_index do |article, index| %>
      <% if index % 3 == 0 %>
  </div>
  <div class="row">
      <% end %>
      <div class="col-sm-4">
        <div class="issue-article" itemscope itemtype="http://schema.org/Article">
          <%= render :partial => "article", :locals => { :article => article } %>
        </div>
      </div>
    <% end %>
  </div>

  <hr />

<% end %>

<% if not @issue.mixedmedia.empty? %>

  <h3>Film, Book &amp; Music Reviews</h3>

  <div class="row">
    <% @issue.mixedmedia.each_with_index do |article, index| %>
      <% if index % 3 == 0 %>
  </div>
  <div class="row">
      <% end %>
      <div class="col-sm-4">
        <div class="issue-article" itemscope itemtype="http://schema.org/Article">
          <%= render :partial => "article", :locals => { :article => article } %>
        </div>
      </div>
    <% end %>
  </div>

  <hr />

<% end %>

<div class="clearfix"></div>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              issues_path, :class => 'btn btn-default' %>
  <% if user_signed_in? and can? :create, Article %>
    <%= link_to 'New Article', new_issue_article_path(@issue), :class => 'btn btn-primary' %>
  <% end %>
</div>

<%= render :partial => "disqus", :object => @issue %>

app/views/issues/zip.html.erb
<h1>Zipped issue: <%= @issue.id %></h1>