config/routes.rb
NI::Application.routes.draw do

  RESPOND_403.each do |r2|
    get "/#{r2}", to: proc { [403, {}, ['']] }
  end

  resources :categories, :only => [:index, :show, :edit, :update]
  get 'update_categories_colours' => 'categories#colours'

  get "guest_passes/index"

  get "subscriptions/update"

  get "settings/index"

  get "settings/update"

  get "/sitemap.xml", :controller => "sitemap", :action => "index"

  get "users/re_sign_in"

  devise_for :users, :controllers => { :registrations => "registrations", :sessions => "sessions", :passwords => "passwords" } #, :path_names => { :sign_up => "subscribe" }

  devise_scope :user do
    get "/uk_login" => "devise/sessions#new_uk"
  end

  post "users/:id(.:format)", :to => 'users#show', :as => :user
  resources :users, :only => [:show]

  resources :subscriptions do
    get :show
    new do
      get :express
    end
  end

  post "issues/:id(.:format)", :to => 'issues#show', :as => :issue

  resources :issues do
    get :import
    get :import_extra
    get :import_images
    get :email
    get :email_non_subscribers
    get :email_others
    get :email_renew
    get :email_special
    get :zip
    post :setup_push_notification
    get :tweet_issue
    get :wall_post_issue
    get :email_issue
    resources :articles do
      resources :favourites, :only => [:create, :destroy]
      resources :guest_passes, :only => [:create, :destroy]
      get :body
      post :body
      post :body_android
      get :import
      get :import_images
      get :generate_from_source
      resources :images do
        collection { post :sort }
      end
      post :send_push_notification
      get :tweet
      get :wall_post
      get :email_article
      get :ios_share
      post :ios_share
      get :android_share
      post :android_share
      get :hide_images
    end
    resources :purchases, :only => [:new, :create, :show] do
      new do
        get :express
      end
    end
  end

  get 'search' => 'articles#search'
  get 'popular' => 'articles#popular'
  get 'quick_reads' => 'articles#quick_reads'

  resource :payment_notifications, :only => [:create]

  resource :push_registrations, only: [:create, :destroy]

  namespace :admin do
    root :to => "base#index"
    get "welcome_email" => "base#welcome_email"
    get "reset_password_instructions_email" => "base#reset_password_instructions_email"
    get "subscription_email" => "base#subscription_email"
    get "magazine_purchase_email" => "base#magazine_purchase_email"
    get "admin_email" => "base#admin_email"
    get "delete_cache" => "base#delete_cache"
    get "users/update_csv" => "users#update_csv"
    get "users/download_csv" => "users#download_csv"
    get "users/search" => "users#search"
    resources :users do
      get :free_subscription
      get :crowdfunding_subscription
      get :media_subscription
      get :make_institutional
      get :free_silent_subscription
      post :free_silent_subscription
      get :become
    end
    resources :subscriptions, :only => [:update]
    resources :settings, :only => [:index, :update], :constraints => { :id => /[a-z_]+/ }
    resources :guest_passes, :only => [:index]
    resources :push_registrations, :only => [:index]
    namespace :push_registrations do
      get :import
    end
    resources :push_notifications, :only => [:index, :destroy]
    namespace :push_notifications do
      post :run_delayed_jobs
      post :send_notifications
    end
  end

  namespace :institution do
    root :to => "base#index"
    resources :users
  end

  get "home/index"
  get "newsstand" => "home#newsstand"
  get "free" => "home#free"
  get "inapp" => "home#inapp"
  get "google_merchant_feed" => "home#google_merchant_feed"
  get "apple_news" => "home#apple_news"
  get "apple-app-site-association" => "home#apple_app_site_association"
  get "rss" => "home#apple_news"
  get "latest_cover" => "home#latest_cover"
  get "tweet_url" => "home#tweet_url"
  get "wall_post_url" => "home#wall_post_url"
  get "email_url" => "home#email_url"

  root :to => 'home#index'

  get '/perma_article/:id' => 'articles#show'

  get 'pages', to: 'pages#index'
  get ':id', to: 'pages#show', as: :page
  patch ':id', to: 'pages#update'#, as: :page
  delete ':id', to: 'pages#destroy'#, as: :page

  resources :pages, except: :show

end

app/helpers/articles_helper.rb
module ArticlesHelper

  def source_to_body(article, options = {})
    debug = options[:debug] or false
    if not article.source.blank?
      doc = Nokogiri::XML(article.source)

      def process_children(e, debug = false)
        e.xpath("*").sort_by{|n| n["order"].to_i}.collect{|e| process_element(e,debug)}.join("")
      end

      def process_element(e, debug = false)
        if e.name == "container"
          if e["element_type"] == "cross_head"
            "<h3>"+process_children(e, debug)+"</h3>"
          elsif e["element_type"] == "cross_head_2"
            "<h4>"+process_children(e, debug)+"</h4>"
          elsif e["element_type"] == "html"
            process_children(e, debug)
          elsif e["element_type"] == "attribution"
            "<div class='attribution'>"+process_children(e, debug)+"</div>"
          elsif e["element_type"] == "pull_quote"
            alignment = e.at_xpath("field[@type='alignment']").text
            "<blockquote class='pull-#{alignment}'>"+process_children(e, debug)+"</blockquote>"
          elsif e["element_type"] == "block_quote"
            "<blockquote class='block-quote'>"+process_children(e, debug)+"</blockquote>"
          elsif e["element_type"] == "box"
            "<div class='box'>"+process_children(e,debug)+"</div>"
          elsif e["element_type"] == "factbox_third_width"
            alignment = e.at_xpath("field[@type='factbox_float']").text.downcase
            "<div class='factbox pull-#{alignment}'>"+process_children(e,debug)+"</div>"
          elsif e["element_type"] == "list"
            "<ul>"+process_children(e,debug)+"</ul>"
          elsif e["element_type"] == "at_a_glance"
            "<div class='at-a-glance'><h3>At a glance</h3><dl class='dl-horizontal'>"+process_children(e,debug)+"</dl></div>"
          elsif e["element_type"] == "star_ratings"
            "<div class='star-ratings'><h3>Star ratings</h3><dl class='dl-horizontal'>"+process_children(e,debug)+"</dl></div>"
          elsif e["element_type"] == "product_profile"
            "<div class='product-profile'>"+process_children(e,debug)+"</div>"
          elsif e["element_type"] == "author_note" or e["element_type"] == "author" or e["element_type"] == "postscript"
            "<div class='author-note'>"+process_children(e,debug)+"</div>"
          elsif e["element_type"] == "worldbeater"
            "<div class='worldbeater'><dl class='dl-horizontal'>"+process_children(e,debug)+"</dl></div>"
          elsif e["element_type"] == "making_waves"
            "<div class='making-waves'><dl class='dl-horizontal'>"+process_children(e,debug)+"</dl></div>"
          elsif e["element_type"] == "related_media" or e["element_type"] == "related_media_graphic"
            media_id = e["related_media_id"]
            image = Image.find_by_media_id(media_id)
            if image.try(:hidden)
              return nil
            end
            media_url = image.try(:data_url, :halfwidth)
            if not image.nil?
              "[File:#{image.try(:id)}]"
            else
              ""
            end
          elsif e["element_type"] == "footnotes"
            "<ol class='footnotes'>"+process_children(e,debug)+"</ol>"
          elsif ["page_no"].include? e["element_type"]
            #ignore
          elsif e["element_type"] == "word_power"
            "<div class='word-power'><div class='all-article-images article-image-cartoon no-shadow'><img alt='Word power by Mitchell and Richardson' title='Word power by Mitchell and Richardson' src='/assets/word-power@2x.jpg' width='300' /></div><dl class='dl-horizontal'>"+process_children(e,debug)+"</dl></div>"
          else
            "[UNKNOWN_CONTAINER{type="+e["element_type"]+"}: "+process_children(e,debug)+" /CONTAINER]" if debug
          end
        elsif e.name == "field"
          if ["paragraph","quote", "block_quote","an_author_note", "author", "postscript_text", "box_deck", "product_information", "factbox_content"].include? e["type"]
            # paragraph-like things
            "<p>#{e.text.gsub(/\n/, " ")}</p>"
          elsif ["attribution"].include? e["type"]
            # block quote attribution
            "<p class='attribution'>#{e.text.gsub(/\n/, " ")}</p>"
          elsif ["list_item"].include? e["type"]
            # list-like things
            "<li>#{e.text.gsub(/\n/, " ")}</li>"
          elsif e["type"].start_with?("aag_")
            # make a nice list of 'at a glance' items
            "<dt>#{e['type'].gsub(/aag_/, '').titlecase}</dt><dd>#{e.text.gsub(/\n/, " ")}</dd>"
          elsif ["attribution_link", "attribution_org"].include? e["type"]
            # attribution
            attribution_link = e.text.gsub(/\n/, "")
            if not attribution_link.include?("http://")
              attribution_link = "http://" + attribution_link
            end
            "<p><a href='#{attribution_link}'>#{attribution_link.gsub(/http:\/\//, " ")}</a></p>"
          elsif e["type"] == "last_profiled"
            @last_profiled_link = e.text
            return
          elsif e["type"] == "last_profiled_link"
            "<dt>Last Profiled</dt><dd><a href='#{@last_profiled_link}'>#{e.text}</a></dd>"
          elsif ["income_distribution", "life_expectancy", "literacy", "position_of_women", "freedom", "sexual_minorities", "politics"].include? e["type"]
            "<dt>#{e['type'].gsub(/_/, ' ').titlecase}</dt><dd>#{e.text}</dd>"
          elsif ["stars", "product_stars"].include? e["type"]
            star = "<i class='icon-star'></i> "
            star_rating = if e.text == "One"
                "#{star}"
              elsif e.text == "Two"
                "#{star}#{star}"
              elsif e.text == "Three"
                "#{star}#{star}#{star}"
              elsif e.text == "Four"
                "#{star}#{star}#{star}#{star}"
              elsif e.text == "Five"
                "#{star}#{star}#{star}#{star}#{star}"
              end
            if e["type"] == "product_stars"
              "<p>NI review: #{star_rating}</p>"
            else
              "<dd>#{star_rating}</dd>"
            end
          elsif e["type"] == "year"
            "<dt class='star-ratings-previous-year'>#{e.text}</dt>"
          elsif e["type"] == "product_link"
            product_link = e.text.gsub(/\n/, "")
            if not product_link.include?("http://")
              product_link = "http://" + product_link
            end
            "<p><a href='#{product_link}'>#{product_link.gsub(/http:\/\//, " ")}</a></p>"
          elsif e["type"] == "html" or e["type"] == "text"
            e.text.gsub(/\n/, " ")
          elsif ["rel_media_caption", "alt_text"].include? e["type"]
            "<div class='new-image-caption'>#{e.text.gsub(/\n/, " ")}</div>"
          elsif e["type"] == "rel_media_credit"
            "<div class='new-image-credit'>#{e.text}</div>"
          elsif e["type"] == "cross_head"
            e.text
          elsif e["type"] == "cross_head_2"
            e.text
          elsif e["type"] == "foot_ref"
            "<li>#{e.text.gsub(/\n/, " ")}</li>"
          elsif e["type"] == "box_title"
            "<h4>#{e.text}</h4>"
          elsif ["wb_name", "wp_job", "wb_reputation", "wb_humour", "wb_cunning", "wb_sources"].include? e["type"]
            "<dt>#{e['type'].gsub(/^w._/, '').titlecase}</dt><dd>#{e.text}</dd>"
          elsif ["interview_with", "talked_to"].include? e["type"]
            "<dt>#{e['type'].gsub(/^w._/, '').titlecase}</dt><dd>#{e.text}</dd>"
          elsif ["issue_number","teaser","deck","page_no","alignment","hold","rel_media_class", "factbox_float"].include? e["type"]
            #ignore 
          elsif ["wp_language"].include? e["type"]
            "<h4>The language of the #{e.text}</h4>"
          elsif ["wp_definition_term"].include? e["type"]
            "<dt>#{e.text}</dt>"
          elsif ["wp_definition_desc"].include? e["type"]
            "<dd>#{e.text}</dd>"
          else
            "[unknown field type "+e["type"]+"]" if debug
          end
        else
          "[unknown tag #{e.name}]" if debug
        end 
      end

      if not article.hide_author_name
        if doc.xpath('//container[@element_type="author_note"]').empty? and doc.xpath('//container[@element_type="author"]').empty? and doc.xpath('//container[@element_type="postscript"]').empty?
          next_order = doc.xpath('//story/elements/*').collect{|e| e["order"].to_i }.max + 1
          doc.at_xpath('//story/elements') << '<container order="'+next_order.to_s+'" element_type="author_note"><field type="an_author_note">'+article.author+'</field></container>'
        end
      end

      return process_children(doc.xpath("//story/elements"),debug)

    end

    return ""

  end

  def expand_image_tags(body, debug = false)
    # Finds [File:xx] and [File:xx|cartoon] in body and converts it to nice div/img code
    body = body.gsub(/\[File:(?<id>\d+)(?:\|(?<all_options>[^\]]*))?\]/i) do 
      id = $~[:id]
      # weird "or" doesnt work here but || does...
      options = $~[:all_options].try(:split,"|") || []
      begin
        image = Image.find(id)

        version = :threehundred
        css_class = "article-image"
        image_width = 300
        credit_div = ""
        caption_div = ""

        if options.include?("full")
          version = nil
          css_class = "all-article-images article-image-cartoon article-image-full"
          image_width = 945
        elsif options.include?("cartoon")
          version = :sixhundred
          css_class = "all-article-images article-image-cartoon"
          image_width = 600
        elsif options.include?("centre")
          version = :threehundred
          css_class = "all-article-images article-image-cartoon article-image-centre"
          image_width = 300
        elsif options.include?("half")
          version = nil
          css_class = "all-article-images article-image-half"
          image_width = 472
        end
        
        if options.include?("ns")

app/views/articles/_category_fields.html.erb
<fieldset>
	<div class="controls">
		<%= f.text_field :name, :class => 'text_field category_autocomplete form-control' %>
		<%= f.hidden_field :_destroy %>
		<%= link_to "remove", '#', class: "remove_fields btn btn-danger" %>
	</div>
</fieldset>

app/views/articles/_disqus.html.erb
<div id="disqus_thread"></div>
<script type="text/javascript">

    var disqus_shortname = 'newint';
    var disqus_category_id = '3158771';
    var disqus_identifier = "<%= issue_article_path(@article.issue, @article) %>";
    var disqus_title = "<%= @article.issue.number %> - <%= @article.title.encode(Encoding.find('ASCII'), {:invalid => :replace, :undef => :replace, :replace => ''}) %>";
    var disqus_url = "<%= issue_article_url(@article.issue, @article) %>";

    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<!-- <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a> -->

app/views/articles/_share_links.html.erb
<p class="share-links"><span class="breadcrumb"><%= link_to "NI #{@issue.number} - #{@article.publication.strftime("%B, %Y")}", issue_path(@issue) %></span><span class="clear-hack"></span>
  <% if user_signed_in? and can? :create, Favourite %>
    <!-- Favourite -->
    <% if article_favourited?(@article) %>
      <%= link_to raw('<i class="fa fa-heart red"></i>'), issue_article_favourite_path(@issue.id, @article.id, favourite_id_for_article(@article)), :method => 'delete', :class => 'article-favourite', :alt => 'Remove from favourites', :title => 'Remove from favourites' %>
    <% else %>
      <%= link_to raw('<i class="fa fa-heart-o"></i>'), issue_article_favourites_path(@issue, @article), :method => 'create', :class => 'article-favourite', :alt => 'Add to favourites', :title => 'Add to favourites' %>
    <% end %>
    <!-- END Favourite -->
  <% end %>
  <% if user_signed_in? and can? :create, GuestPass %>
    <!-- Sharing options -->
    <% if article_has_a_guest_pass?(@article) %>
      <%= link_to raw('<i class="fa fa-share"></i>'), issue_article_guest_pass_path(@issue.id, @article.id, guest_pass_id_for_article(@article)), :method => 'delete', :class => 'article-favourite', :alt => 'Delete this guest pass', :title => 'Delete this guest pass' %>
      <!-- Guest pass link -->
      <%= link_to 'Guest pass to share', generate_guest_pass_link_string(current_user.guest_passes.select{|s| (s.article.id == @article.id)}.last), :alt => 'Right-click and copy this link to share it with friends.', :title => 'Right-click and copy this link to share it with friends.' %>
      <!-- Email button -->
	    <%= link_to raw('<i class="fa fa-envelope"></i>'), issue_article_email_article_path(@issue,@article), :class => 'article-favourite', :alt => 'Email this article to a friend', :title => 'Email this article to a friend' %>
    <% else %>
      <%= link_to raw('<i class="fa fa-share"></i>'), issue_article_guest_passes_path(@issue, @article), :method => 'create', :class => 'article-favourite', :alt => 'Share this article with a friend.', :title => 'Share this article with a friend.' %>
    <% end %>
    <!-- Tweet button -->
    <%= link_to raw('<i class="fa fa-twitter"></i>'), issue_article_tweet_path(@issue,@article, :text => strip_tags(@article.title)), :class => 'article-favourite', :alt => 'Tweet about this article', :title => 'Tweet about this article', :target => "_blank" %>
    <!-- Facebook button -->
    <%= link_to raw('<i class="fa fa-facebook-square"></i>'), issue_article_wall_post_path(@issue,@article, :text => strip_tags(@article.title)), :class => 'article-favourite', :alt => 'Share this article on Facebook', :title => 'Share this article on Facebook', :target => "_blank" %>
    <!-- END Social buttons -->
    <!-- END Sharing options -->
    <!-- iOS app link -->
    <% link_to retina_image_tag("iphone-dark.png", :alt => "Open '#{@article.title}' in the New Internationalist magazine app for Android or iOS mobile devices.", :title => "Open '#{@article.title}' in the New Internationalist magazine app for Android or iOS mobile devices.", :size => "14x24", :class => 'ios-issue-page'), app_link(issue_article_path(@issue, @article)) %>
    <!-- END iOS app link -->
  <% end %>
</p>

app/views/articles/index.html.erb
<%- model_class = Article -%>
<div class="page-header">
  <h1>All <%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
  <h3>From the issue <%= link_to @issue.title, issue_path(@issue) %></h3>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <% if can? :update, @issue %>
        <th><%= model_class.human_attribute_name(:id) %></th>
      <% end %>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:teaser) %></th>
      <th><%= model_class.human_attribute_name(:author) %></th>
      <th><%= model_class.human_attribute_name(:publication) %></th>
      <!-- <th><%= model_class.human_attribute_name(:body) %></th> -->
      <% if can? :update, @issue %>
        <th><%= model_class.human_attribute_name(:issue_id) %></th>
        <th><%= model_class.human_attribute_name(:trialarticle) %></th>
        <th><%= model_class.human_attribute_name(:created_at) %></th>
      <% end %>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @issue.articles.each do |article| %>
      <tr>
        <% if can? :update, article %>
          <td><%= link_to article.id, issue_article_path(@issue,article) %></td>
        <% end %>
        <td><%= link_to article.title, issue_article_path(@issue,article) %></td>
        <td><%= article.teaser %></td>
        <td><%= article.author %></td>
        <td><%= link_to article.publication.strftime("%B, %Y"), issue_path(@issue) %></td>
        <!-- <td><%= article.body %></td> -->
        <% if can? :update, @issue %>
          <td><%= link_to article.issue_id, issue_path(@issue) %></td>
          <td><%= article.trialarticle %></td>
          <td><%= article.created_at.strftime("%d %B, %Y") %></td>
        <% end %>
        <td>
          <% if can? :read, article %>
            <%= link_to 'Read', issue_article_path(article.issue,article), :class => 'btn btn-default btn-xs' %>
          <% else %>
            <%= link_to 'Buy', new_issue_purchase_path(article.issue), :class => 'btn btn-xs btn-primary' %>
          <% end %>
          <% if can? :update, article %>
            <%= link_to 'Edit', edit_issue_article_path(article.issue,article), :class => 'btn btn-primary btn-xs' %>
          <% end %>
          <% if can? :destroy, article %>
            <%= link_to 'Destroy', issue_article_path(article.issue,article), confirm: 'Are you sure?', method: :delete, :class => 'btn btn-xs btn-danger' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/articles/new.html.erb
<%- model_class = Article -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/articles/quick_reads.html.erb
<%- model_class = Article -%>

<% if can? :update, Article %>
<div class="edit-issue-buttons">
  <%= link_to "Flush quick reads cache", admin_delete_cache_path(cache: "quick_reads"), :class => 'btn btn-xs btn-danger', data: { confirm: 'Are you sure?'} %>
</div>
<% end %>

<div class="page-header">
  <h1><%= @page_title %></h1>
  <h3><%= @page_description %></h3>
</div>

<div class="row">
  <% if @quick_reads %>
    <% @quick_reads.each_with_index do |article, index| %>
      <% if index % 3 == 0 %>
</div>
<div class="row">
      <% end %>
      <div class="col-sm-4">
      <% if article.guest_passes.count > 0 %>
        <%= render :partial => "popular_article", :locals => { :article => article, :guest_pass => article.guest_passes.first } %>
      <% else %>
        <%= render :partial => "categories/category_article", :locals => { :article => article } %>
      <% end %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/articles/search.html.erb
<%- model_class = Article -%>
<div class="page-header">
  <h1>Article search</h1>
  <h3>Search for an article from the New Internationalist magazine archive.</h3>
</div>

<div class="article-search">
  <%= form_tag search_path, :class => 'form-search form-inline', method: :get do %>
      <div class="input-append">
        <%= text_field_tag :query, params[:query], :placeholder => 'Article search', :class => "span2 search-query form-control" %>
        <%= submit_tag "Search", name: nil, :class => 'btn btn-default' %>
      </div>
      <p>You might also like to <%= link_to 'browse articles by category', categories_path %>.<br />
      Or limit your search to <%= link_to "Magazine main themes", issues_path %>.</p>
  <% end %>
</div>

<h4>Search results<% if params[:query] %> for: <span class="red"><%= params[:query] %></span><% else %>:<% end %></h4>

<div class="row">
  <% if @articles %>
    <% @articles.sort_by(&:publication).reverse.each_with_index do |article, index| %>
      <% if index % 3 == 0 %>
</div>
<div class="row">
      <% end %>
      <div class="col-sm-4">
        <%= render :partial => "home/home_article", :locals => { :article => article } %>
      </div>
    <% end %>
  <% end %>
</div>

<%= paginate @articles %>

<hr />
<h4>Search results in a table<% if params[:query] %> for: <span class="red"><%= params[:query] %></span><% else %>:<% end %></h4>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Article title</th>
      <th>Description</th>
      <th><%= model_class.human_attribute_name(:author) %></th>
      <th>Published</th>
      <!-- <th><%= model_class.human_attribute_name(:body) %></th> -->
      <th>Magazine</th>
      <!-- <th><%= model_class.human_attribute_name(:trialarticle) %></th> -->
      <!-- <th><%= model_class.human_attribute_name(:created_at) %></th> -->
      <th>Link</th>
    </tr>
  </thead>
  <tbody>
    <% @articles.sort_by(&:publication).reverse.each do |article| %>
      <tr>
        <td><%= link_to highlight(article.title, @query_array), issue_article_path(article.issue,article) unless article.issue.nil? %></td>
        <td><%= simple_format highlight(article.teaser, @query_array) %></td>
        <td><%= highlight(article.author, @query_array) %></td>
        <td><%= article.publication.strftime("%B, %Y") %></td>
        <!-- <td><%= article.body %></td> -->
        <td><%= link_to article.issue.number, issue_path(article.issue) unless article.issue.nil? %></td>
        <!-- <td><%= article.trialarticle %></td> -->
        <!-- <td><%=l article.created_at %></td> -->
        <td>
          <% if can? :read, article %>
            <%= link_to 'Read', issue_article_path(article.issue,article), :class => 'btn btn-default btn-xs' unless article.issue.nil? %>
          <% else %>
            <%= link_to 'Buy', new_issue_purchase_path(article.issue), :class => 'btn btn-xs btn-primary' unless article.issue.nil? %>
          <% end %>
          <% if can? :update, article %><%= link_to 'Edit', edit_issue_article_path(article.issue,article), :class => 'btn btn-primary btn-xs' unless article.issue.nil? %><% end %>
          <% if can? :destroy, article %><%= link_to 'Destroy', issue_article_path(article.issue,article), confirm: 'Are you sure?', method: :delete, :class => 'btn btn-xs btn-danger' unless article.issue.nil? %><% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @articles %>

app/views/articles/show.amp.erb
<script type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "NewsArticle",
  "mainEntityOfPage": {
    "@type": "WebPage",
    "@id": "<%= issue_article_url(@issue, @article) %>"
  },
  "headline": "<%= @article.title %>",
  <% if @article.first_image %>
    "image": {
      "@type": "ImageObject",
      "url": "<%= @article.first_image.try(:data).to_s %>",
      "height": <%= @article.first_image.try(:height) %>,
      "width": <%= @article.first_image.try(:width) %>
    },
  <% end %>
  "datePublished": "<%= @article.publication.to_time.iso8601 %>",
  "dateModified": "<%= @article.updated_at.to_time.iso8601 %>",
  "author": {
    "@type": "Person",
    "name": "<%= @article.author %>"
  },
  "publisher": {
    "@type": "Organization",
    "name": "New Internationalist",
    "logo": {
      "@type": "ImageObject",
      "url": "<%= image_url("new-internationalist-google-amp-600x60.png") %>",
      "width": 600,
      "height": 60
    }
  },
  "description": "<%= strip_tags(@article.teaser) %>"
}
</script>

<div class="logo">
  <a href="<%= root_url %>">New Internationalist</a>
</div>

<h1><%= @article.title %></h1>
<h2><%= simple_format @article.teaser %></h2>
<div class="breadcrumb">
  <%= link_to "NI #{@issue.number} - #{@article.publication.strftime("%B, %Y")}", issue_path(@issue) %>
  <!-- <br /><%= link_to "Read this on the desktop site", issue_article_url(@issue, @article) %> -->
</div>

<% if @article.body.blank? %>
  <%= simple_format expand_image_tags(source_to_body(@article, :debug => current_user.try(:admin?)), :debug => "amp") %>
<% else %>
  <%= simple_format expand_image_tags(@article.body, :debug => "amp") %>
<% end %>

<hr />

<% if not @related_articles.blank? %>
  <h4>Also on this theme</h4>
  <ul>
  <% @related_articles.first(10).each do |article| %>
    <li><%= link_to article.title, issue_article_path(article.issue, article) %></li>
  <% end %>
  </ul>
<% end %>