config/routes.rb
NI::Application.routes.draw do

  RESPOND_403.each do |r2|
    get "/#{r2}", to: proc { [403, {}, ['']] }
  end

  resources :categories, :only => [:index, :show, :edit, :update]
  get 'update_categories_colours' => 'categories#colours'

  get "guest_passes/index"

  get "subscriptions/update"

  get "settings/index"

  get "settings/update"

  get "/sitemap.xml", :controller => "sitemap", :action => "index"

  get "users/re_sign_in"

  devise_for :users, :controllers => { :registrations => "registrations", :sessions => "sessions", :passwords => "passwords" } #, :path_names => { :sign_up => "subscribe" }

  devise_scope :user do
    get "/uk_login" => "devise/sessions#new_uk"
  end

  post "users/:id(.:format)", :to => 'users#show', :as => :user
  resources :users, :only => [:show]

  resources :subscriptions do
    get :show
    new do
      get :express
    end
  end

  post "issues/:id(.:format)", :to => 'issues#show', :as => :issue

  resources :issues do
    get :import
    get :import_extra
    get :import_images
    get :email
    get :email_non_subscribers
    get :email_others
    get :email_renew
    get :email_special
    get :zip
    post :setup_push_notification
    get :tweet_issue
    get :wall_post_issue
    get :email_issue
    resources :articles do
      resources :favourites, :only => [:create, :destroy]
      resources :guest_passes, :only => [:create, :destroy]
      get :body
      post :body
      post :body_android
      get :import
      get :import_images
      get :generate_from_source
      resources :images do
        collection { post :sort }
      end
      post :send_push_notification
      get :tweet
      get :wall_post
      get :email_article
      get :ios_share
      post :ios_share
      get :android_share
      post :android_share
      get :hide_images
    end
    resources :purchases, :only => [:new, :create, :show] do
      new do
        get :express
      end
    end
  end

  get 'search' => 'articles#search'
  get 'popular' => 'articles#popular'
  get 'quick_reads' => 'articles#quick_reads'

  resource :payment_notifications, :only => [:create]

  resource :push_registrations, only: [:create, :destroy]

  namespace :admin do
    root :to => "base#index"
    get "welcome_email" => "base#welcome_email"
    get "reset_password_instructions_email" => "base#reset_password_instructions_email"
    get "subscription_email" => "base#subscription_email"
    get "magazine_purchase_email" => "base#magazine_purchase_email"
    get "admin_email" => "base#admin_email"
    get "delete_cache" => "base#delete_cache"
    get "users/update_csv" => "users#update_csv"
    get "users/download_csv" => "users#download_csv"
    get "users/search" => "users#search"
    resources :users do
      get :free_subscription
      get :crowdfunding_subscription
      get :media_subscription
      get :make_institutional
      get :free_silent_subscription
      post :free_silent_subscription
      get :become
    end
    resources :subscriptions, :only => [:update]
    resources :settings, :only => [:index, :update], :constraints => { :id => /[a-z_]+/ }
    resources :guest_passes, :only => [:index]
    resources :push_registrations, :only => [:index]
    namespace :push_registrations do
      get :import
    end
    resources :push_notifications, :only => [:index, :destroy]
    namespace :push_notifications do
      post :run_delayed_jobs
      post :send_notifications
    end
  end

  namespace :institution do
    root :to => "base#index"
    resources :users
  end

  get "home/index"
  get "newsstand" => "home#newsstand"
  get "free" => "home#free"
  get "inapp" => "home#inapp"
  get "google_merchant_feed" => "home#google_merchant_feed"
  get "apple_news" => "home#apple_news"
  get "apple-app-site-association" => "home#apple_app_site_association"
  get "rss" => "home#apple_news"
  get "latest_cover" => "home#latest_cover"
  get "tweet_url" => "home#tweet_url"
  get "wall_post_url" => "home#wall_post_url"
  get "email_url" => "home#email_url"

  root :to => 'home#index'

  get '/perma_article/:id' => 'articles#show'

  get 'pages', to: 'pages#index'
  get ':id', to: 'pages#show', as: :page
  patch ':id', to: 'pages#update'#, as: :page
  delete ':id', to: 'pages#destroy'#, as: :page

  resources :pages, except: :show

end

app/views/shared/_account_sign_up.html.erb
<% if not current_user %>
  <hr />

  <div class="row">
    <div class="col-sm-12 social-networks">
      <span class="social-media"><i class="fa fa-envelope"></i></span>
      <h4>Join our monthly email list, create a free account</h4>
      <%= simple_form_for(resource, :as => resource_name, :url => registration_path(resource_name), :html => {:class => 'form-inline' }) do |f| %>
        <%= f.error_notification %>

        <div class="inputs shared-sign-up">
          <%= f.input :email, :required => true, :label => false, :placeholder => 'Email address' %>
          <%= f.input :username, :required => true, :label => false, :placeholder => 'Username' %>
          <%= f.input :password, :required => true, :label => false, :placeholder => 'Password' %>
          <%= f.input :password_confirmation, :required => true, :label => false, :placeholder => 'Confirm your password' %>
        </div>

        <div class="actions">
          <%= f.button :submit, "Sign up" %>
          <%= render :partial => "shared/privacy" %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/shared/_amp_analytics.amp.erb
<amp-analytics type="googleanalytics">
  <script type="application/json">
    {
      "vars": {
        "account": "<%= Rails.env.production? ? ENV["GOOGLE_ANALYTICS_PRODUCTION"] : ENV["GOOGLE_ANALYTICS_DEVELOPMENT"] %>"
      },
      "triggers": {
        "default pageview": {
          "on": "visible",
          "request": "pageview",
          "vars": {
            "title": "<%= page.title %>"
          }
        }
      }
    }
  </script>
</amp-analytics>

app/views/shared/_disqus.html.erb
<script type="text/javascript">
	// Display comment count.
    var disqus_shortname = 'newint';

    (function () {
        var s = document.createElement('script'); s.async = true;
        s.type = 'text/javascript';
        s.src = '//' + disqus_shortname + '.disqus.com/count.js';
        (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
    }());
</script>

app/views/shared/_fb_events.html.erb
<% unless session[:fb_events].nil? %>
  <% session[:fb_events].each do |event|%>
  	<!-- Facebook Conversion Code for digital.newint.com.au events -->
		<script>
		!function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
		n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
		n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
		t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
		document,'script','https://connect.facebook.net/en_US/fbevents.js');

		fbq('init', <%= ENV["FACEBOOK_APP_ID"] %>);
	<% if event[:action] == ENV["FACEBOOK_PAGEVIEW"] %>
		fbq('track', "<%= ENV["FACEBOOK_PAGEVIEW"] %>");
	<% end %>
		</script>
		<noscript><img height="1" width="1" style="display:none"
		src="https://www.facebook.com/tr?id=<%= ENV["FACEBOOK_APP_ID"] %>&amp;ev=<%= event[:action]%>&amp;cd[value]=<%= event[:amount]%>&amp;cd[currency]=AUD&amp;noscript=1"
		/></noscript>

  <% end %>
<% end %>

<% session[:fb_events] = Array.new %>

app/views/shared/_footer.html.erb
<div class="footer">

  <div class="row">
    <div class="col-sm-4">
      <!-- <div class="home-image">
        <%= link_to retina_image_tag('utne-winner.png', :alt => 'Awards New Internationalist magazine has won', :title => 'Awards New Internationalist magazine has won', :width => 75, :height => 96), page_path("awards") %>
      </div> -->
      <%= link_to retina_image_tag("new-internationalist.png", :alt => "New Internationalist - The world unspun", :title => "New Internationalist - The world unspun", width: 150, class: "brand"), root_path %>
      <% if user_signed_in? and current_user.try(:subscriber?) or current_user.try(:admin?) %>
        <p>Welcome back to the New Internationalist digital edition. Thanks for subscribing, we really appreciate it. If you have any feedback or suggestions for new features we can add, our contact details are in the footer. Enjoy reading the magazine.</p>
      <% else %>
        <p>The <b>New Internationalist</b> is an independent monthly not-for-profit magazine that reports on action for global justice. We believe in putting people before profit, in climate justice, tax justice, equality, social responsibility and human rights for all.</p>
        <% if not request.format.symbol == :amp %>
        <div class="home-donate">
          <p>If you like the magazine and support what we do, perhaps you'd like to donate some money to help us reach a wider audience?</p>
          <p><form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
            <input type="hidden" name="cmd" value="_s-xclick">
            <input type="hidden" name="hosted_button_id" value="GSMBBM2JT2W28">
            <button type="submit" class="btn btn-default"><i class="fa fa-heart"></i> Donate using PayPal</button>
          </form></p>
        </div>
        <% end %>
      <% end %>
    </div>
    <div class="col-sm-4">
      <h5>Site map:</h5>
      <ul>
        <li><% if current_user.nil? %><%= link_to "Subscribe", page_path("subscribe") %><% else %><%= link_to "Subscribe", new_subscription_path %><% end %></li>
        <li><%= link_to "Magazine archive", issues_path %></li>
        <li><%= link_to "Search", search_path %></li>
        <li><%= link_to "Categories", categories_path %></li>
        <li><%= link_to "Mobile applications", page_path("apps") %></li>
        <li><%= link_to "Help", page_path("help") %></li>
        <li><%= link_to "RSS feed", rss_url(format: :xml) %></li>
        <li><%= link_to "How to leak", page_path("how-to-leak") %></li>
        <li><%= link_to "SecureDrop", page_path("securedrop") %></li>
        <li><%= link_to "Warrant canary", "/canary.txt" %></li>
      </ul>
    </div>
    <div class="col-sm-4">
      <h5>Find us:</h5>
      <ul>
        <li>Twitter: <a href="https://twitter.com/<%= ENV["TWITTER_NAME"] %>">@<%= ENV["TWITTER_NAME"] %></a></li>
        <li>Facebook: <a href="https://facebook.com/<%= ENV["FACEBOOK_PAGE_NAME"] %>">@<%= ENV["FACEBOOK_PAGE_NAME"] %></a></li>
        <li>Google+: <a href="https://plus.google.com/+<%= ENV["GOOGLE_PLUS_NAME"] %>">+<%= ENV["GOOGLE_PLUS_NAME"] %></a></li>
        <li>Instagram: <a href="https://instagram.com/<%= ENV["INSTAGRAM_NAME"] %>">@<%= ENV["INSTAGRAM_NAME"] %></a></li>
        <li>Youtube: <a href="https://www.youtube.com/user/<%= ENV["YOUTUBE_NAME"] %>/videos"><%= ENV["YOUTUBE_NAME"] %></a></li>
        <li>Apple: <a href="<%= ENV["ITUNES_APP_LINK"] %>">App Store</a></li>
        <li>Android: <a href="<%= ENV["GOOGLE_PLAY_APP_LINK"] %>">Play Store</a></li>
      </ul>
      <h5>Contact us:</h5>
      <ul>
        <li>Anonymously: <%= link_to "SecureDrop server", page_path("securedrop") %></li>
        <li>Email: <a href="mailto:<%= ENV["DEVISE_EMAIL_ADDRESS"] %>?Subject=Question from digital.newint.com.au"><%= ENV["DEVISE_EMAIL_ADDRESS"] %></a></li>
        <li>PGP Public Key and Fingerprint:<br /><%= link_to "#{ENV['PGP_PUBLIC_KEY_FINGERPRINT']}", "#{ENV['PGP_PUBLIC_KEY_LINK']}" %></li>
        <li>Phone: <%= ENV["PHONE_NUMBER"] %></li>
        <li><%= raw(ENV["STREET_ADDRESS"]) %></li>
      </ul>
    </div>
  </div>

  <div class="copyright">
    <p>&copy; Copyright <b>New Internationalist</b> 1973-<%= DateTime.now.year %>. Except where otherwise noted, content on this site is <a href="http://creativecommons.org/licenses/by-nc-nd/3.0/">licensed</a> under <a href="http://creativecommons.org">Creative Commons</a>.</p>
    <p>Except where otherwise noted, images on this site are &copy; the attributed photographer/illustrator or representative agency.</p>
  </div>
</div>

app/views/shared/_ga_events.html.erb
<% unless session[:events].nil? %>
  <% session[:events].each do |event|%>
  	<script type="text/javascript">
			// Push Google Analytics event
			ga('send', 'event', '<%= event[:category]%>', '<%= event[:action]%>', '<%= event[:label]%>');
		</script>
  <% end %>
<% end %>

<% session[:events] = Array.new %>

app/views/shared/_privacy.html.erb
<div class="privacy-policy">
	<p>Read our <%= link_to 'privacy policy', page_path('ios', anchor: 'privacy') %></p>
</div>