config/routes.rb
NI::Application.routes.draw do

  RESPOND_403.each do |r2|
    get "/#{r2}", to: proc { [403, {}, ['']] }
  end

  resources :categories, :only => [:index, :show, :edit, :update]
  get 'update_categories_colours' => 'categories#colours'

  get "guest_passes/index"

  get "subscriptions/update"

  get "settings/index"

  get "settings/update"

  get "/sitemap.xml", :controller => "sitemap", :action => "index"

  get "users/re_sign_in"

  devise_for :users, :controllers => { :registrations => "registrations", :sessions => "sessions", :passwords => "passwords" } #, :path_names => { :sign_up => "subscribe" }

  devise_scope :user do
    get "/uk_login" => "devise/sessions#new_uk"
  end

  post "users/:id(.:format)", :to => 'users#show', :as => :user
  resources :users, :only => [:show]

  resources :subscriptions do
    get :show
    new do
      get :express
    end
  end

  post "issues/:id(.:format)", :to => 'issues#show', :as => :issue

  resources :issues do
    get :import
    get :import_extra
    get :import_images
    get :email
    get :email_non_subscribers
    get :email_others
    get :email_renew
    get :email_special
    get :zip
    post :setup_push_notification
    get :tweet_issue
    get :wall_post_issue
    get :email_issue
    resources :articles do
      resources :favourites, :only => [:create, :destroy]
      resources :guest_passes, :only => [:create, :destroy]
      get :body
      post :body
      post :body_android
      get :import
      get :import_images
      get :generate_from_source
      resources :images do
        collection { post :sort }
      end
      post :send_push_notification
      get :tweet
      get :wall_post
      get :email_article
      get :ios_share
      post :ios_share
      get :android_share
      post :android_share
      get :hide_images
    end
    resources :purchases, :only => [:new, :create, :show] do
      new do
        get :express
      end
    end
  end

  get 'search' => 'articles#search'
  get 'popular' => 'articles#popular'
  get 'quick_reads' => 'articles#quick_reads'

  resource :payment_notifications, :only => [:create]

  resource :push_registrations, only: [:create, :destroy]

  namespace :admin do
    root :to => "base#index"
    get "welcome_email" => "base#welcome_email"
    get "reset_password_instructions_email" => "base#reset_password_instructions_email"
    get "subscription_email" => "base#subscription_email"
    get "magazine_purchase_email" => "base#magazine_purchase_email"
    get "admin_email" => "base#admin_email"
    get "delete_cache" => "base#delete_cache"
    get "users/update_csv" => "users#update_csv"
    get "users/download_csv" => "users#download_csv"
    get "users/search" => "users#search"
    resources :users do
      get :free_subscription
      get :crowdfunding_subscription
      get :media_subscription
      get :make_institutional
      get :free_silent_subscription
      post :free_silent_subscription
      get :become
    end
    resources :subscriptions, :only => [:update]
    resources :settings, :only => [:index, :update], :constraints => { :id => /[a-z_]+/ }
    resources :guest_passes, :only => [:index]
    resources :push_registrations, :only => [:index]
    namespace :push_registrations do
      get :import
    end
    resources :push_notifications, :only => [:index, :destroy]
    namespace :push_notifications do
      post :run_delayed_jobs
      post :send_notifications
    end
  end

  namespace :institution do
    root :to => "base#index"
    resources :users
  end

  get "home/index"
  get "newsstand" => "home#newsstand"
  get "free" => "home#free"
  get "inapp" => "home#inapp"
  get "google_merchant_feed" => "home#google_merchant_feed"
  get "apple_news" => "home#apple_news"
  get "apple-app-site-association" => "home#apple_app_site_association"
  get "rss" => "home#apple_news"
  get "latest_cover" => "home#latest_cover"
  get "tweet_url" => "home#tweet_url"
  get "wall_post_url" => "home#wall_post_url"
  get "email_url" => "home#email_url"

  root :to => 'home#index'

  get '/perma_article/:id' => 'articles#show'

  get 'pages', to: 'pages#index'
  get ':id', to: 'pages#show', as: :page
  patch ':id', to: 'pages#update'#, as: :page
  delete ':id', to: 'pages#destroy'#, as: :page

  resources :pages, except: :show

end

app/models/category.rb
class Category < ActiveRecord::Base

  validates_uniqueness_of :name

  has_many :article_categorisations
  has_many :articles, :through => :article_categorisations

  after_commit :flush_cache

  def self.create_from_element(article,element)
    assets = 'http://bricolage.sourceforge.net/assets.xsd'
    c = nil
    if Category.where(:name => element).empty?
      # Try a looser search
      loose_search = Category.where("name ilike ?", "%#{element.parameterize}%")
      if not loose_search.empty?
        # Match the first loose category, user will check if it's suitable
        c = loose_search.first
      end
    end

    if c.nil?
      # Fallback to first_or_create
      c = Category.where(:name => element).first_or_create
    end
    article.categories << c unless article.categories.include?(c)
    return c
  end

  def latest_published_article
    Category.cached_category_articles(self.id).last
  end

  def first_articles(number)
    Category.cached_category_articles(self.id).reverse.first(number)
  end

  def self.cached_category_articles(id)
    Rails.cache.fetch([name, id]) { find(id).articles.select(&:published).sort_by(&:publication) }
  end

  def flush_cache
    Rails.cache.delete([self.class.name, id])
  end

  def display_name
    read_attribute(:display_name) or generate_display_name
  end

  def short_display_name
    # Beware, ugly hack. :-)
    display_name.split(">").last.try(:strip)
  end

  def generate_display_name
    # From /columns/letters-from/ To "Letters from"
    # From /themes/aid/development/ To "Aid > Development"
    # From /features/special/ To "Special features"
    # From /features/web-exclusive/ To "Web exclusives"
    # From /columns/media/music/ To "Media > Music"
    # From /blog/books/ To "Blog > Books"
    # "Not > implemented (#{name})"
    pretty_name = name.gsub(/\/(themes|sections)\/(.*)\//) {$2.gsub(/-/," ").titleize}
    if pretty_name.include?("/")
      pretty_name = pretty_name.split("/").select{|s|not s.blank?}.map{|s| s.titleize}.join(" > ")
    end
    pretty_name
  end

  def colour_as_hex
    if colour
      return "#%06x" % colour
    else
      return "#FFFFFF"
    end
  end

  def self.hsv_to_rgb(h, s, v)
    h_i = (h*6).to_i
    f = h*6 - h_i
    p = v * (1 - s)
    q = v * (1 - f*s)
    t = v * (1 - (1 - f) * s)
    r, g, b = v, t, p if h_i==0
    r, g, b = q, v, p if h_i==1
    r, g, b = p, v, t if h_i==2
    r, g, b = p, q, v if h_i==3
    r, g, b = t, p, v if h_i==4
    r, g, b = v, p, q if h_i==5
    [(r*255).to_i, (g*255).to_i, (b*255).to_i]
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  # Cancan authorisation
  load_and_authorize_resource

  # Cache index as it takes a long time to compute
  caches_action :index, layout: false

  def index
    @categories = @categories.sort_by(&:display_name)
    @issues = Issue.all

    # Set meta tags
    @page_title = "Article categories"
    @page_description = "A list of categories and themes covered by articles in New Internationalist magazine."

    set_meta_tags :title => @page_title,
                  :description => @page_description,
                  :keywords => "themes, categories, category, new, internationalist, magazine, digital, edition",
                  :canonical => categories_url,
                  :alternate => [
                    {:href => "android-app://#{ENV['GOOGLE_PLAY_APP_PACKAGE_NAME']}/newint/categories"}, 
                    {:href => "ios-app://#{ENV['ITUNES_APP_ID']}/newint/categories"},
                    {:href => rss_url(format: :xml), :type => 'application/rss+xml', :title => 'RSS'}
                  ],
                  :fb => {
                    :app_id => ENV["FACEBOOK_APP_ID"]
                  },
                  :open_graph => {
                    :title => @page_title,
                    :description => @page_description,
                    #:type  => :magazine,
                    :url   => categories_url,
                    :image => Issue.latest.try(:cover_url, :thumb2x).to_s,
                    :site_name => "New Internationalist Magazine Digital Edition"
                  },
                  :twitter => {
                    :card => "summary",
                    :site => "@#{ENV["TWITTER_NAME"]}",
                    :creator => "@#{ENV["TWITTER_NAME"]}",
                    :title => @page_title,
                    :description => @page_description,
                    :image => {
                      :src => Issue.latest.try(:cover_url, :thumb2x).to_s
                    }
                  }
  end

  def show
    @articles = Kaminari.paginate_array(Category.cached_category_articles(@category.id).reverse).page(params[:page]).per(Settings.category_pagination)

    # Set meta tags
    @page_title = "#{@category.short_display_name} articles"
    @page_description = "All New Internationalist articles about #{@category.short_display_name}, ordered by date."
    @category_image = @category.try(:latest_published_article).try(:first_image).try(:data).to_s

    set_meta_tags :site => 'New Internationalist',
                  :title => @page_title,
                  :description => @page_description,
                  :keywords => "#{@category.short_display_name}, new, internationalist, magazine, digital, edition",
                  :canonical => category_url(@category),
                  :alternate => [
                    {:href => "android-app://#{ENV['GOOGLE_PLAY_APP_PACKAGE_NAME']}/newint/categories"}, 
                    {:href => "ios-app://#{ENV['ITUNES_APP_ID']}/newint/categories"},
                    {:href => rss_url(format: :xml), :type => 'application/rss+xml', :title => 'RSS'}
                  ],
                  :fb => {
                    :app_id => ENV["FACEBOOK_APP_ID"]
                  },
                  :open_graph => {
                    :title => @page_title,
                    :description => @page_description,
                    #:type  => :magazine,
                    :url   => category_url(@category),
                    :image => @category_image,
                    :site_name => "New Internationalist Magazine Digital Edition"
                  },
                  :twitter => {
                    :card => "summary",
                    :site => "@#{ENV["TWITTER_NAME"]}",
                    :creator => "@#{ENV["TWITTER_NAME"]}",
                    :title => @page_title,
                    :description => @page_description,
                    :image => {
                      :src => @category_image
                    },
                    :app => {
                      :name => {
                        :iphone => ENV["ITUNES_APP_NAME"],
                        :ipad => ENV["ITUNES_APP_NAME"]
                      },
                      :id => {
                        :iphone => ENV["ITUNES_APP_ID"],
                        :ipad => ENV["ITUNES_APP_ID"]
                      },
                      :url => {
                        :iphone => "newint://categories/#{@category.id}",
                        :ipad => "newint://categories/#{@category.id}"
                      }
                    }
                  }
  end

  def edit
    if @category.colour
      # @category.colour = "##{@category.colour.to_s(16)}"
      @category.colour = @category.colour_as_hex
    end
  end

  def create
    # Expire the cache
    expire_action :action => :index
  end

  def update
    # Expire the cache
    expire_action :action => :index
    expire_action :action => :show

    if params[:category][:colour] and not params[:category][:colour].empty?
      params[:category][:colour] = params[:category][:colour].match("[0-9a-f]+")[0].hex
    end
    logger.info params
    respond_to do |format|
      if @category.update_attributes(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def colours
    Category.all.sort_by(&:display_name).each_with_index{|c,i| 
      c.colour = Category.hsv_to_rgb(i/(Category.count+1).to_f,0.5,1).collect{|n| "%02x" % n}.join.hex
      c.save
    }
    redirect_to categories_path, notice: 'Colours were updated.' 
  end

  private

  def category_params
    params.require(:category).permit(:name, :display_name, :colour)
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<% cache(category, :expires_in => 1.day) do %>
  <% if category.latest_published_article %>
  <tr>
    <!-- <td><%= link_to category.id, category_path(category) %></td> -->
    <td style="background-color: <%= category.colour_as_hex %>">&nbsp;</td>
    <td><%= link_to category.display_name, category_path(category) %></td>
    <td><%= link_to category.latest_published_article.title, issue_article_path(category.latest_published_article.issue, category.latest_published_article) %></td>
    <td><%= category.latest_published_article.publication.strftime("%B, %Y") %></td>
  </tr>
  <% end %>
<% end %>

app/views/categories/_category_article.html.erb
				<div class="home-keynote">
					<% if can? :read, article %>
						<!-- Can read this article, so link to it -->
						<% if not article.featured_image.blank? %>
					    <%= link_to retina_image_tag(article.featured_image_url(:fullwidth).to_s, :class => 'article-thumb', :alt => "#{strip_tags(article.featured_image_caption)}", :title => "#{strip_tags(article.featured_image_caption)}", :width => 300, :itemprop => "image"), issue_article_path(article.issue,article) %>
					  <% elsif article.first_image %>
					    <%= link_to retina_image_tag(article.first_image.data_url(:threehundred).to_s, :class => 'article-thumb', :alt => "#{strip_tags((article.first_image.try('caption') ? article.first_image.caption : article.title + ' ') + (article.first_image.try('credit') ? article.first_image.credit : ''))}", :title => "#{strip_tags((article.first_image.try('caption') ? article.first_image.caption : article.title + ' ') + (article.first_image.try('credit') ? article.first_image.credit : ''))}", :width => 300, :itemprop => "image"), issue_article_path(article.issue,article) %>
					  <% else %>
					  	<%= link_to retina_image_tag('fallback/threehundred_no_image.jpg', :class => 'article-thumb', :alt => "#{strip_tags(article.title)}", :title => "#{strip_tags(article.title)}", :width => 300, :itemprop => "image"), issue_article_path(article.issue,article) %>
					  <% end %>
					  <div class="home-keynote-text">
					  	<h3><%= link_to highlight(article.title, @query_array), issue_article_path(article.issue,article) %></h3>
							<h4><%= simple_format highlight(article.teaser, @query_array) %></h4>
							<p><%= link_to 'Read this article', issue_article_path(article.issue,article), :class => 'btn btn-default btn-xs' %></p>
							<div class="category-article-issue">
								<%= link_to retina_image_tag(article.issue.cover_url(:tiny).to_s, :class => 'issue-cover', :alt => "NI #{article.issue.number} - #{article.issue.title} - #{article.issue.release.strftime("%B, %Y")}", :title => "NI #{article.issue.number} - #{article.issue.title} - #{article.issue.release.strftime("%B, %Y")}", :rel => "tooltip", :size => "53x75"), issue_path(article.issue) %>
								<h5 class="breadcrumb"><%= link_to "#{article.issue.number} - #{article.issue.release.strftime("%B, %Y")}", issue_path(article.issue) %><br /><%= render :partial => "home/home_share_links", :locals => { :article => article } %></h5>
							</div>
					  </div>
					<% else %>
						<!-- Can't read this article, so link to buy it -->
						<% if not article.featured_image.blank? %>
					    <%= link_to retina_image_tag(article.featured_image_url(:fullwidth).to_s, :class => 'article-thumb', :alt => "#{strip_tags(article.featured_image_caption)}", :title => "#{strip_tags(article.featured_image_caption)}", :width => 300, :itemprop => "image"), new_issue_purchase_path(article.issue) %>
					  <% elsif article.first_image %>
					    <%= link_to retina_image_tag(article.first_image.data_url(:threehundred).to_s, :class => 'article-thumb', :alt => "#{strip_tags((article.first_image.try('caption') ? article.first_image.caption : article.title + ' ') + (article.first_image.try('credit') ? article.first_image.credit : ''))}", :title => "#{strip_tags((article.first_image.try('caption') ? article.first_image.caption : article.title + ' ') + (article.first_image.try('credit') ? article.first_image.credit : ''))}", :width => 300, :itemprop => "image"), new_issue_purchase_path(article.issue) %>
					  <% else %>
					  	<%= link_to retina_image_tag('fallback/threehundred_no_image.jpg', :class => 'article-thumb', :alt => "#{strip_tags(article.title)}", :title => "#{strip_tags(article.title)}", :width => 300, :itemprop => "image"), new_issue_purchase_path(article.issue) %>
					  <% end %>
					  <div class="home-keynote-text">
					  	<h3><%= link_to highlight(article.title, @query_array), new_issue_purchase_path(article.issue) %></h3>
							<h4><%= simple_format highlight(article.teaser, @query_array) %></h4>
							<p><%= link_to 'Buy this magazine', new_issue_purchase_path(article.issue), :class => 'btn btn-success btn-xs' %></p>
							<div class="category-article-issue">
								<%= link_to retina_image_tag(article.issue.cover_url(:tiny).to_s, :class => 'issue-cover', :alt => "NI #{article.issue.number} - #{article.issue.title} - #{article.issue.release.strftime("%B, %Y")}", :title => "NI #{article.issue.number} - #{article.issue.title} - #{article.issue.release.strftime("%B, %Y")}", :rel => "tooltip", :size => "53x75"), issue_path(article.issue) %>
								<h5 class="breadcrumb"><%= link_to "#{article.issue.number} - #{article.issue.release.strftime("%B, %Y")}", issue_path(article.issue) %><br /><%= render :partial => "home/home_share_links", :locals => { :article => article } %></h5>
							</div>
					  </div>
					<% end %>
				</div>

app/views/categories/_form.html.erb
<%= simple_form_for @category, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :name %>
  <%= f.input :colour, input_html: { type: 'color', style: 'width: 200px'} %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                category_path(@category), :class => 'btn btn-default' %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<%- model_class = Category -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/categories/index.html.erb
<%- model_class = Category -%>

<% if can? :update, @category %>
<div class="edit-issue-buttons">
  <%= link_to 'Update colours', update_categories_colours_path, :class => 'btn btn-xs btn-success' %>
</div>
<% end %>

<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
  <h3>A list of categories and themes covered by articles in New Internationalist magazine. <%= link_to retina_image_tag("iphone-dark.png", :alt => "Open these categories in the New Internationalist magazine app for Android or iOS mobile devices.", :title => "Open these categories in the New Internationalist magazine app for Android or iOS mobile devices.", :size => "14x24", :class => 'ios-issue-page'), app_link(categories_path) %></h3>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <!-- <th><%= model_class.human_attribute_name(:id) %></th> -->
      <th>&nbsp;</th>
      <th>Category name</th>
      <th>Latest article published</th>
      <th>Date published</th>
    </tr>
  </thead>
  <tbody>
    <%= render :partial => "category", :collection => @categories %>
  </tbody>
</table>

app/views/categories/new.html.erb
<%- model_class = Category -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/categories/show.html.erb
<%- model_class = Category -%>

<% if can? :update, @category %>
<div class="edit-issue-buttons">
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
                edit_category_path(@category), :class => 'btn btn-primary btn-xs' %>
  <% if can? :destroy, @category %>
    <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
          category_path(@category),
          :method => 'delete',
          :data => {:confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?'))},
          :class => 'btn btn-xs btn-danger' %>
  <% end %>
</div>
<% end %>

<div class="page-header">
  <h1><%= @category.display_name.gsub('>', '/') %></h1>
  <h3>Articles about <%= @category.short_display_name %>, ordered by date. <%= link_to retina_image_tag("iphone-dark.png", :alt => "Open '#{@category.short_display_name}' in the New Internationalist magazine app for Android or iOS mobile devices.", :title => "Open '#{@category.short_display_name}' in the New Internationalist magazine app for Android or iOS mobile devices.", :size => "14x24", :class => 'ios-issue-page'), app_link(category_path(@category)) %></h3>
</div>

<div class="row">
  <% if @articles %>
    <% @articles.each_with_index do |article, index| %>
      <% if index % 3 == 0 %>
</div>
<div class="row">
      <% end %>
      <div class="col-sm-4">
        <%= render :partial => "category_article", :locals => { :article => article } %>
      </div>
    <% end %>
    <div class="col-sm-12">
      <%= paginate @articles %>
    </div>
  <% end %>
</div>

<hr />
<h4>Articles in this category displayed as a table:</h4>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Article title</th>
      <th>From magazine</th>
      <th>Publication date</th>
    </tr>
  </thead>
  <tbody>
    <% @articles.each do |article| %>
      <tr itemscope itemtype="http://schema.org/Article">
        <td itemprop="name"><%= link_to article.title, issue_article_path(article.issue,article), :itemprop => "url" %></td>
        <td><%= link_to article.issue.title, issue_path(article.issue) %></td>
        <td itemprop="dateCreated"><%= article.publication.strftime("%B, %Y") %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @articles %>

<div class="form-actions">

  <nav>
    <ul class="breadcrumb">
      <li><%= link_to "Home", root_path %> <span class="divider">></span></li>
      <li><%= link_to "Categories", categories_path %> <span class="divider">></span></li>
      <li><%= @category.short_display_name %></li>
    </ul>
  </nav>

  <%= link_to t('.back', :default => t("helpers.links.back")),
              categories_path, :class => 'btn btn-default'  %>
</div>